littlektframework/littlekt

- core/src/commonMain/kotlin/com/lehaine/littlekt/input/InputMultiplexer.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/DisplayTest.kt
> Add InputMultiplexer that combines multiple input sources into a single output

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- build.gradle.kts
- convention-plugins/build.gradle.kts
- convention-plugins/src/main/kotlin/littlekt.convention.publication.gradle.kts
- core/build.gradle.kts
- samples/build.gradle.kts
- settings.gradle.kts
* Add convention-plugins module and plugin for publishing to sonatype
* Add deploy GitHub action
> Add sonatype publishing and gradle build script changes

- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/SceneGraph.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/component/InputEvent.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/internal/NodeList.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/Camera.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/input/Input.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/util/viewport/ExtendViewport.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/util/viewport/ScalingViewports.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/util/viewport/Viewport.kt
- core/src/jvmMain/kotlin/com/lehaine/littlekt/input/LwjglInput.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/DisplayTest.kt
scene graph: add ui input events for touch down, up, and draggin
scene graph: throw error if scene hasn' been initialized when trying to render or update
camera: add project and unprojec vec2f methods
> Add UI input event handlers to SceneGraph

- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/SceneGraph.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/Node.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/BaseButton.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/Button.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/Container.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/Control.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/Color.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/util/signals.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/util/viewport/Viewport.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/DisplayTest.kt
* Add a `BaseButton` base control for buttons to inherit
* Add a simple `Button` control that displays text and a background using a `TextureSlice`
* Update `signal` classes to allow for list connections vs just being mapped by an object
* Closes #39
> A BaseButton and Button control to UI scene graph

- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/component/Drawable.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/component/NinePatchDrawable.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/component/TextureSliceDrawable.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/component/ext.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/Button.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/Color.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/NinePatch.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/font/FontCache.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/DisplayTest.kt
* **ui**: add Drawable interface with TextureSlice and NinePatch implementations (closes #52)
* **ui**: update Button control to use a Drawable vs only a TextureSlice
* **color**: fix miscalculation when multiplying a color by another color
> Add Drawable implementation

- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/component/Theme.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/Panel.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/PanelContainer.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/DisplayTest.kt
* UI: Implement `Panel` control (closes #59)
* UI: Implement `PanelContainer` control
> Implement Panel and PanelContainer Controls

- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/SceneGraph.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/Button.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/Container.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/Control.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/Label.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/PaddedContainer.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/DisplayTest.kt
* Fix #60 
* Update `PaddedContainer` to use correct offsets when positioning children
* Update `Control` to computer margins by default vs anchors.
> UI: Fix issues where a child `Control` size isn't updating to match the `Container` size settings

- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/internal/InternalResources.kt
- core/src/jsMain/kotlin/com/lehaine/littlekt/WebGLContext.kt
- core/src/jvmMain/kotlin/com/lehaine/littlekt/LwjglContext.kt
> Refactor the way `InternalResources` are loaded

- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/Node.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/component/OverrideMap.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/component/Theme.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/BaseButton.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/Container.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/Control.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/Label.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/DisplayTest.kt
* Clean up `Node` callback naming and usage
* Add `onThemeChanged` callback to `Control` (closes #68)
> Scene graph cleanup

- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/component/Drawable.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/component/Theme.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/ProgressBar.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/Range.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/DisplayTest.kt
* Add abstract base control `Range`. (closes #71)
* Add `ProgressBar` UI control (closes #72)
> Add `Range` and `ProgressBar` UI Controls

- CHANGELOG.md
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/font/BitmapFontCache.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/font/FontCache.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/font/GlyphLayout.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/util/utils.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/DisplayTest.kt
> Add text truncation to `GlyphLayout`

- .gitignore
- core/src/androidMain/kotlin/com/lehaine/littlekt/AndroidClipboard.kt
- core/src/androidMain/kotlin/com/lehaine/littlekt/AndroidContext.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/Context.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/util/Clipboard.kt
- core/src/jsMain/kotlin/com/lehaine/littlekt/JsClipboard.kt
- core/src/jsMain/kotlin/com/lehaine/littlekt/WebGLContext.kt
- core/src/jvmMain/kotlin/com/lehaine/littlekt/JvmClipboard.kt
- core/src/jvmMain/kotlin/com/lehaine/littlekt/LwjglContext.kt
> Add clipboard functionality

- core/build.gradle.kts
- core/src/androidMain/kotlin/com/lehaine/littlekt/AndroidContext.kt
- core/src/androidMain/kotlin/com/lehaine/littlekt/input/AndroidInput.kt
- core/src/androidMain/kotlin/com/lehaine/littlekt/view/LittleKtSurfaceView.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/input/Input.kt
- core/src/jsMain/kotlin/com/lehaine/littlekt/input/JsInput.kt
- core/src/jvmMain/kotlin/com/lehaine/littlekt/input/LwjglInput.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/DisplayTest.kt
> input: add showing/hiding soft keyboard for Android

- core/src/androidMain/kotlin/com/lehaine/littlekt/input/AndroidInput.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/SceneGraph.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/component/InputEvent.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/component/Theme.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/Node2D.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/Control.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/LineEdit.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/Color.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/input/InputCache.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/input/InputMultiplexer.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/input/InputProcessor.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/input/InputQueueProcessor.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/input/internal/InternalInputEventType.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/util/datastructure/Pool.kt
- core/src/jsMain/kotlin/com/lehaine/littlekt/input/JsInput.kt
- core/src/jvmMain/kotlin/com/lehaine/littlekt/input/LwjglInput.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/DisplayTest.kt
> Add new `LineEdit` node

- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/AnimationPlayer.kt
anim player: refactor the current 'start()' function to be named 'resume()'
anim player: add new 'start()' function the will restart any running animaton to the first frame
anim player: add 'restart()' function that is an alias for 'start()'
> Update `AnimationPlayer` start, resume, and stop logic.

- gradle/libs.versions.toml
gradle: update kotlin to 1.7.20
gradle: update kotlinx-serialization to 1.4.0
gradle: update kotlinx-atomicfu to 0.18.4
> Update Kotlin to latest version plus additional dependencies

- CHANGELOG.md
- core/src/androidMain/kotlin/com/lehaine/littlekt/input/AndroidInput.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/input/Input.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/input/InputCache.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/input/gesture/GestureController.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/input/gesture/GestureProcessor.kt
- core/src/jsMain/kotlin/com/lehaine/littlekt/input/JsInput.kt
- core/src/jvmMain/kotlin/com/lehaine/littlekt/input/LwjglInput.kt
- samples/src/androidMain/kotlin/com/lehaine/littlekt/samples/AppActivity.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/GestureControllerTest.kt
- samples/src/jvmMain/kotlin/com/lehaine/littlekt/samples/GestureControllerTest.kt
`GestureController` is a `InputProcessor` that handles detecting gestures such as tapping, flinging, panning, zooming, and pinching and provides an interface / listener `GestureProcessor`.
> Add `GestureProcessor` and `GestureController`

- CHANGELOG.md
- README.md
- gradle.properties
> Prepare version 0.5.3

- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/Particle.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/ParticleSimulator.kt
particle: convert dataX fields to float
particle: make color field immutable
particle: remove colorBits field
> Particle Updates

- CHANGELOG.md
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/internal/NodeList.kt
> Update `NodeList` to handle `Node.updateInterval` values below 1

- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/Node.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/ui/Control.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/SceneGraphTest.kt
> Fix `Node.onPostEnterScene` not being invoked after being added to a scene after initialization

- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/Node.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/internal/NodeList.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/ui/BoxContainer.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/ui/ScrollContainer.kt
Also includes new method for removing & destroying all of a nodes children. Closes #193
> Revert NodeList to use separate collection when adding new nodes

- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/GL.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/HdpiMode.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/shader/generator/GlslGenerator.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/shader/shaders/ModelShaders.kt
- core/src/jvmMain/kotlin/com/lehaine/littlekt/JvmPlatform.kt
- core/src/jvmMain/kotlin/com/lehaine/littlekt/LwjglContext.kt
- core/src/jvmMain/kotlin/com/lehaine/littlekt/LwjglGL.kt
- core/src/jvmMain/kotlin/com/lehaine/littlekt/LwjglGraphics.kt
- core/src/jvmMain/kotlin/com/lehaine/littlekt/input/LwjglInput.kt
* Fixes retina support / HDPI mode on Macs
* Fixes versioning checks for Macs
* Fixes EXT related calls on Macs
> Fix Mac support

- core/src/commonMain/kotlin/com/lehaine/littlekt/input/InputCache.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/input/InputQueueProcessor.kt
- core/src/jvmMain/kotlin/com/lehaine/littlekt/input/LwjglInput.kt
- samples/src/jvmMain/kotlin/com/lehaine/littlekt/samples/InputTest.kt
> Update `InputQueueProcessor` to clear events pool even if no `InputProcessor` exists

- core/build.gradle.kts
- core/src/commonMain/kotlin/com/littlekt/file/compression/Compression.kt
- core/src/commonMain/kotlin/com/littlekt/file/compression/CompressionGZIP.kt
- core/src/commonTest/kotlin/com/littlekt/file/compression/compression.kt
- core/src/jsMain/kotlin/com/littlekt/file/compression/CompressionGZIP.js.kt
- core/src/jsMain/kotlin/com/littlekt/file/compression/streams.external.kt
- core/src/jvmAndroidMain/kotlin/com/littlekt/file/compression/CompressionGZIP.jvmAndroid.kt
- gradle/libs.versions.toml
Completes the gzip part of #118 .
> file: add Compression interface and CompressionGZIP implementations for jvmAndroid & js

- core/src/commonMain/kotlin/com/littlekt/graphics/g3d/Model.kt
- core/src/commonMain/kotlin/com/littlekt/graphics/g3d/ModelBatch.kt
- core/src/commonMain/kotlin/com/littlekt/graphics/g3d/material/DepthSliceMaterial.kt
- core/src/commonMain/kotlin/com/littlekt/graphics/g3d/material/Material.kt
- core/src/commonMain/kotlin/com/littlekt/graphics/g3d/shader/DepthSliceShader.kt
- core/src/commonMain/kotlin/com/littlekt/graphics/g3d/util/CameraComplexBuffers.kt
- core/src/commonMain/kotlin/com/littlekt/graphics/g3d/util/DepthSliceMaterialPipelineProvider.kt
- core/src/commonMain/kotlin/com/littlekt/graphics/g3d/util/shader/CommonSubShaderFunctions.kt
- core/src/commonMain/kotlin/com/littlekt/graphics/g3d/util/shader/DepthSliceMaterialBuilder.kt
- core/src/commonMain/kotlin/com/littlekt/graphics/g3d/util/shader/FragmentShaderBuilder.kt
- examples/src/commonMain/kotlin/com/littlekt/examples/SimpleGltfExample.kt
- examples/src/commonMain/kotlin/com/littlekt/examples/utils.kt
add CameraComplexBuffers
update Material to allow for nullable binding group
add Model to set mesh primitives material
fix get_tile function logic in shader code
> add DepthSliceMaterial & shader
