- core/src/commonMain/kotlin/com/lehaine/littlekt/AssetProvider.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/Game.kt
- core/src/jvmMain/kotlin/com/lehaine/littlekt/LwjglContext.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/DisplayTest.kt
* Add an asset cache to `AssetProvider`
* Prevent loading the exact same `VfsFile` if already loading or in progress
* Fix an issue with updating the audio context in `LwjglContext`
*  Make `createDefaultLoaders` and `loaders` map public and mutable
* Remove the internal `AssetProvider` in the `Game` class to allow custom provider
> Clean up Game and AssetProvider classes

- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/Color.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/font/FontCache.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/font/GlyphLayout.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/DisplayTest.kt
* glyph layout: clear colors, width, height, and glyph count on reset
* glyph layout: fix issue with not adding the current color to the colors list
* font cache: fix issue of calculating the glyph offset when tinting
* Fixes #53
> Fix FontCache/GlyphLayout color issues

- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/Container.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/Control.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/DisplayTest.kt
* Add `MouseFilter` to allow preventing / ignoring / handling input events on a `Control`. Closes #67
> Add `MouseFilter` logic to UI

- core/src/commonMain/kotlin/com/lehaine/littlekt/Context.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/Graphics.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/SceneGraph.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/BufferObjects.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/GL.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/TextureData.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/shader/generator/GlslGenerator.kt
- core/src/jsMain/kotlin/com/lehaine/littlekt/WebGL.kt
- core/src/jsMain/kotlin/com/lehaine/littlekt/WebGLContext.kt
- core/src/jsMain/kotlin/com/lehaine/littlekt/WebGLGraphics.kt
- core/src/jsMain/kotlin/com/lehaine/littlekt/graphics/gl/GlVertexArray.kt
- core/src/jvmMain/kotlin/com/lehaine/littlekt/LwjglContext.kt
- core/src/jvmMain/kotlin/com/lehaine/littlekt/LwjglGL.kt
- core/src/jvmMain/kotlin/com/lehaine/littlekt/LwjglGraphics.kt
* Refactor `GLVersion` to own class and clean up handling of GL30 and WebGL checks
* Update WebGL and WebGL2 to use VAOs
* Closes #8
> Refactor GL version handling

- core/build.gradle.kts
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/TextureAtlas.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/util/MutableTextureAtlas.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/MutableAtlasTest.kt
- samples/src/jvmMain/kotlin/com/lehaine/littlekt/samples/MutableAtlasTest.kt
Allows building a `TextureAtlas` at run time by combining separate textures and existing `TextureAtlas` objects into a single newly created `TextureAtlas`.
Adds a few extensions to `TextureAtlas` called `combine` that takes in either a `Texture`, `TextureSlice` or a `TextureAtlas`.
> Add a MutableTextureAtlas for packing textures into a TextureAtlas

- core/src/androidMain/kotlin/com/lehaine/littlekt/input/AndroidInput.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/SceneGraph.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/Node.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/component/InputEvent.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/Node2D.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/BaseButton.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/Button.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/CenterContainer.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/Container.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/Control.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/HBoxContainer.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/Label.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/LineEdit.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/NinePatchRect.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/PaddedContainer.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/Panel.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/PanelContainer.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/ProgressBar.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/TextureRect.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/VBoxContainer.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/input/Input.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/input/InputCache.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/input/InputMapController.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/input/InputMapProcessor.kt
- core/src/jsMain/kotlin/com/lehaine/littlekt/input/JsInput.kt
- core/src/jvmMain/kotlin/com/lehaine/littlekt/input/LwjglInput.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/DisplayTest.kt
* Rename `InputMultiplexer` to `InputMapController`
* Add new `InputMapProcessor` interface with `onAction` callbacks used with `InputMapController`
* Update `InputMapController` to handle `Pointer` types as a binding
* Update `InputMapController` to handle key modifiers in a binding (SHIFT, CTRL, and ALT)
* Update `SceneGraph` to use an `InputMapController` and input actions
* Update `SceneGraph` focus keybinds to use action bindings
* Add a helper methods to set default UI input action bindings to for `SceneGraph`
> Refactor `InputMultipexer` to `InputMapController` and to handle input action callbacks

- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/NinePatchRect.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/node2d/ui/TextureProgress.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/NinePatch.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/DisplayTest.kt
* add: `TextureProgress` control node (closes #106)
* update: `NinePatch` to support setting source rectangle
* update: `NinePatchRect` control node to use a `TextureSlice` vs using a `NinePatch` directly.
> Add `TextureProgress` Control

- core/build.gradle.kts
- gradle/libs.versions.toml
`arm64` for Windows, MacOS, and Linux.
> Add arm64 dependencies for LWJGL

- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/CanvasItem.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/internal/NodeList.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/YSortTest.kt
Previously, sorting with `ySort` or any custom sort would sort the `nodes` list directly which would change the order in which the `Node.update()` method is invoked. This change allows to keep the original update order while using a custom sort to allow for rendering in a different order.
> Update `NodeList` to keep original children order while using custom render sort

- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/ui/Button.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/ui/Control.kt
A new cache for each of the theme types (drawable, font, color, constants) have a new map collection in the `Control` node. This cache is populated the first time `getThemeX` is called.
For example:
`getThemeDrawable()` will return a result and then is cached in the `drawableCache` map. Any subsequent calls to `getThemeDrawable()` will first check in the `drawableCache` map and return a result if it exists. 
When a theme owners theme changes, the theme owners and its child control nodes will all have their caches cleared.
When a theme value is overridden, any calls to `getThemeX` will pull from the overridden maps first and then the cache maps before searching for a theme owner / fallback value.
> Add theme related caching to `Control` nodes

- CHANGELOG.md
- core/src/androidMain/kotlin/com/lehaine/littlekt/AndroidContext.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/AssetProvider.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/Context.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/Scene.kt
- core/src/jsMain/kotlin/com/lehaine/littlekt/WebGLContext.kt
- core/src/jvmMain/kotlin/com/lehaine/littlekt/LwjglContext.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/DisplayTest.kt
Causes breaking changes for any suspend function called in any of these methods.
The following are now non-suspending:
* `Context.onRender`
* `Context.onPostRender`
* `Context.onPostRunnable`
* `Context.onResize`
* `AssetProvider.update`
> Refactor `Context` main game loop, render, and resize methods to be non-suspending

- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/Node.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/internal/NodeList.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/SceneGraphTest.kt
Adds new child tree positioning methods. `NodeList` updated to use just an array list to handle the indexing as the multiple collections were not able to handle the movement changes.
- `sendChildToTop()`
- `sendChildAtTopTop()`
- `sendChildToBottom()`
- `sendChildAtToBottom()`
- `addChildAt()`
- `swapChildren()`
- `swapChildrenAt()`
> Update NodeList and Node child methods

- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/SceneGraph.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/ViewportCanvasLayer.kt
> Fix multiple calls to `debugRender` with nested `ViewportCanvasLayer`.

- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/SceneGraph.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/CanvasItem.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/CanvasLayer.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/FrameBufferNode.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/Node.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/resource/InputEvent.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/ui/BaseButton.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/ui/Control.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/ui/FrameBufferContainer.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/ui/LineEdit.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graph/node/ui/ScrollContainer.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/CanvasCameraTest.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/SceneGraphNestedViewportsTest.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/UiPlayground.kt
- samples/src/commonMain/kotlin/com/lehaine/littlekt/samples/UiTest.kt
- samples/src/jvmMain/kotlin/com/lehaine/littlekt/samples/SceneGraphNestedViewportsTest.kt
This includes all CanvasLayer subtypes such as FrameBufferNode & ViewportCanvasLayer.
Closes #204
> Fix incorrect coordinates calculation with nested CanvasLayers

- core/src/jsMain/kotlin/com/lehaine/littlekt/input/JsInput.kt
- core/src/jvmMain/kotlin/com/lehaine/littlekt/input/LwjglInput.kt
> Update touched input to default to POINTER1 if touched pointers are empty

- core/src/androidMain/kotlin/com/lehaine/littlekt/AndroidGL.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/FrameBuffer.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/GL.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/gl/GlFrameBuffer.kt
- core/src/jsMain/kotlin/com/lehaine/littlekt/WebGL.kt
- core/src/jsMain/kotlin/com/lehaine/littlekt/graphics/gl/GlFrameBuffer.kt
- core/src/jvmAndroidMain/kotlin/com/lehaine/littlekt/graphics/gl/GlFrameBuffer.kt
- core/src/jvmMain/kotlin/com/lehaine/littlekt/LwjglGL.kt
fbo: add new GlFrameBuffer.EmptyGlFrameBuffer companion object function
gl: update GL.getBoundFrameBuffer to allow for optional 'out' param to prevent constant creation of new GlFrameBuffers
gl: update backend GlFrameBuffers to allow changing referene
fbo: optimze FrameBuffer to reuse GlFrameBuffer objects instead of creating new one on each begin() and end() call
> Add ability to reuse `GlFrameBuffer` and optimize `FrameBuffer` to not create a `GlFrameBuffer` object per `begin()` & `end()` call

- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/FrameBuffer.kt
Multiple calls to `glGetIntegerv` caused poor performance when using multiple FBOs. Removing such kills the ability to nest FBOs upon each other.
`FrameBuffer.end()` will now bind to the default framebuffer and takes an optional viewport position and size.
> Remove `FrameBuffer` nestability due to poor performance.

- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/shader/ShaderParameter.kt
- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/shader/ShaderProgram.kt
`ShaderProgram.getAttrib()` will now return a `-1` if the attribute doesn't exist in the list.
`ShaderProgram.getUniform()` will now return a `null` if the `UniformLocation` doesn't exist.
> Remove `ShaderProgram` `getAttrib()` and `getUniform()` from throwing an `IllegalStateException`

- core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/g2d/tilemap/tiled/TiledTilesLayer.kt
As in #240, make tiles public so that I can access a list of the co-ordinates of every tile that has been placed in a layer.
> Make tiles public

- core/src/commonMain/kotlin/com/littlekt/graphics/g2d/BatchExt.kt
- core/src/commonMain/kotlin/com/littlekt/graphics/g2d/SpriteBatch.kt
- core/src/commonMain/kotlin/com/littlekt/graphics/g2d/SpriteBatchShader.kt
- core/src/commonMain/kotlin/com/littlekt/graphics/g2d/SpriteCache.kt
- core/src/commonMain/kotlin/com/littlekt/graphics/g2d/SpriteCacheShader.kt
- core/src/commonMain/kotlin/com/littlekt/graphics/shader/Shader.kt
- core/src/commonMain/kotlin/com/littlekt/graphics/shader/SpriteShader.kt
- core/src/commonMain/kotlin/com/littlekt/graphics/webgpu/command.kt
- core/src/commonMain/kotlin/com/littlekt/util/Numbers.kt
- core/src/jsMain/kotlin/com/littlekt/graphics/webgpu/command.js.kt
- core/src/jsMain/kotlin/com/littlekt/graphics/webgpu/gpu.external.classes.kt
- core/src/jvmMain/kotlin/com/littlekt/graphics/webgpu/command.jvm.kt
- core/src/jvmMain/kotlin/com/littlekt/graphics/webgpu/webgpu.jvm.kt
- examples/src/commonMain/kotlin/com/littlekt/examples/RenderSpriteBatchAndMultipleShadersExample.kt
- examples/src/commonMain/kotlin/com/littlekt/examples/RunnerUtils.kt
- examples/src/commonMain/kotlin/com/littlekt/examples/SpriteBatchMultiPassExample.kt
- gradle.properties
* Also fixes JVM Adapter & Device limits initialization
* updates wgpu to `0.19.4.1`
> core: add dynamic uniform camera handling to SpriteShader, SpriteBatchShader, and SpriteBatch

- core/src/commonMain/kotlin/com/littlekt/graphics/g2d/SpriteBatch.kt
- core/src/commonMain/kotlin/com/littlekt/graphics/g2d/TextureAtlas.kt
- core/src/commonMain/kotlin/com/littlekt/graphics/g2d/TextureSlice.kt
- core/src/commonMain/kotlin/com/littlekt/util/MutableTextureAtlas.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/ui/TextureRect.kt
core: rename TextureSlice originalSize to actualSize
> core: update TextureAtlas to flip the offsetY coord, when parsing, to be relative to the bottom of the image rather than the top

- CHANGELOG.md
- core/src/commonMain/kotlin/com/littlekt/file/vfs/MimeType.kt
- core/src/commonMain/kotlin/com/littlekt/file/vfs/PathInfo.kt
- gradle/libs.versions.toml
- Update `kotlin` from `2.0.0` to `2.1.0`
- Update `kotlinx-serialization` from `1.7.0` to `1.7.3`
- Update `kotlinx.atomicfu` from `0.24.0` to `0.26.1`
- Update `LWJGL` from `3.3.3` to `3.3.4`
> bump versions on dependencies

- core/src/jsMain/kotlin/com/littlekt/file/JsByteSequenceStream.kt
`JsByteSeuqnceStream` would call `buffer.flip()` in `init {}` causing things like `hasRemaining()` and `readChunk` to not read anything due to the `buffer.remaining` coming back as `0`. This sequence now assumes the buffer is in a readable state.
> js: fix JsByteSequenceStream flipping a buffer on init

- examples/src/commonMain/kotlin/com/littlekt/examples/HelloSceneGraphExample.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/CanvasItem.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/resource/Drawable.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/resource/EmptyDrawable.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/resource/NinePatchDrawable.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/resource/TextureSliceDrawable.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/ui/BoxContainer.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/ui/Button.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/ui/CanvasLayerContainer.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/ui/CenterContainer.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/ui/Control.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/ui/Label.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/ui/LineEdit.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/ui/NinePatchRect.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/ui/PaddedContainer.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/ui/Panel.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/ui/PanelContainer.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/ui/ProgressBar.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/ui/ScrollBar.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/ui/ScrollContainer.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/ui/TextureProgress.kt
- scene-graph/src/commonMain/kotlin/com/littlekt/graph/node/ui/TextureRect.kt
- Add `CanvasItem.pivotX` and `CanvasItem.pivotY` that accepts values from `0f` and `1f`. `0f, 0f` being bottom-left, by default. `1f,1f` being top-right.
- Add `Control.originX` and `Control.originY` which is the calculation of `width * pivotX` and `height * pivotY`. These values are used in the rendering and when containers fit children.
```kotlin
button {
// moves anchor point to center of parent
anchorX = 0.5f
anchorY = 0.5f
// moves pivot to center of control
pivotX = 0.5f
pivotY = 0.5f
text = "Press me!"
}
node2d {
pivotX = 0.5f
pivotY = 0.5f
val width = 50f
val height = 100f
onRender += {
// node2d doesn't have a built-in width or height so we would need to calculate it ourselves
val originX = width * pivotX
val originY = height * pivotY
batch.draw(slice, x = globalX - originX, y …
```
> scene-graph: add pivot values to CanvasItem

- core/src/commonMain/kotlin/com/littlekt/graphics/g2d/shape/PathDrawer.kt
The function previously used path.size instead of the passed in capacity
(fix untested)
> Fix open no join paths

- core/src/commonMain/kotlin/com/littlekt/AssetProvider.kt
- core/src/commonMain/kotlin/com/littlekt/file/gltf/GltfModelConfig.kt
- core/src/commonMain/kotlin/com/littlekt/file/gltf/GltfModelGenerator.kt
- core/src/commonMain/kotlin/com/littlekt/file/vfs/VfsLoaders.kt
- examples/src/commonMain/kotlin/com/littlekt/examples/ModelInstancingExample.kt
- examples/src/commonMain/kotlin/com/littlekt/examples/PBRExample.kt
- examples/src/commonMain/kotlin/com/littlekt/examples/SimpleGltfExample.kt
- examples/src/commonMain/kotlin/com/littlekt/examples/utils.kt
- Adds a `GltfModelMaterialStrategy` for handling a primitive with a glTF material
- Has two implementations:
- `PBRMaterialStrategy`: for PBR rendering
- `UnlitMaterialStrategy`: for simple unlit rendering
- Adds a `GltfModelFallbackMaterialStrategy` for handling when a glTF primitive does not have a material.
-  `UnlitMaterialFallbackStrategy`: simple white texture coloring fallback.
> add functionality to add own Materials creation strategies based off glTF material during loading
